# Generated by Django 3.0.4 on 2020-05-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='applicantincome',
            new_name='coapplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='credithistory',
            new_name='creditHistory',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='dependants',
            new_name='dependents',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='graduatededucation',
            new_name='graduateEducation',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanamt',
            new_name='loanAmt',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanterm',
            new_name='loanTerm',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='area',
            new_name='propertyArea',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='selfemployed',
            new_name='selfEmployed',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='coapplicatincome',
        ),
        migrations.AddField(
            model_name='approvals',
            name='applicantIncome',
            field=models.IntegerField(default=150),
        ),
    ]
